### ISSUE TITLE
Debian 2.1 Slink?

### ISSUE THREAD

**Issue by jas4711** [debuerreotype/docker-debian-eol-artifacts#2]
Hi! Having access to old releases is useful, thanks for this service!  Would it be possible to add 2.1 Slink too?  What prevents it from being supported?

**Comment by tianon** [comment]
Unfortunately, we can't `debootstrap` slink; potato is as far back as we can go. 😔

**Comment by tianon** [comment]
Some good news here is that in [debuerreotype 0.14](https://github.com/debuerreotype/debuerreotype/releases/tag/0.14) (specifically https://github.com/debuerreotype/debuerreotype/pull/125), I have managed to successfully create `slink` tarballs, but it was a bit involved so I haven't had a chance to push anything here yet. :see_no_evil:

**Comment by tianon** [comment]
:eyes:

https://github.com/debuerreotype/docker-debian-eol-artifacts/tree/dist-slink

https://hub.docker.com/r/debian/eol/tags?name=slink

:tada:
