### ISSUE TITLE
stretch is missing

### ISSUE THREAD

**Issue by stamepicmorg** [debuerreotype/docker-debian-eol-artifacts#4]
My [build is broken](https://github.com/EpicMorg/docker-scripts/actions/runs/3261955154/jobs/5357982744) because no tag `stretch` in `debian/eol` [hub](https://hub.docker.com/r/debian/eol/tags?page=1&name=stretch).

**Comment by tianon** [comment]
Thanks for the reminder!  It's fixed now. :+1:

**Comment by stamepicmorg** [comment]
Thank you for support ❤️
