### ISSUE TITLE
Wheezy apt-get update fails

### ISSUE THREAD

**Issue by twagaman-onebridge** [debuerreotype/docker-debian-eol-artifacts#6]
This may be a bug in Docker itself, however, only with this wheezy image, I am unable to execute apt-get update with a failure "Sub-process http received a segmentation fault".

I checked and made sure that the sources.list referred to archive, and it does. According to this forums post from docker's forums: [https://forums.docker.com/t/running-apt-get-on-debian-wheezy-gives-me-a-seg-fault/121346](https://forums.docker.com/t/running-apt-get-on-debian-wheezy-gives-me-a-seg-fault/121346)

I am unsure if this is an issue with Docker or the image. From Jessie on, everything works fine.

A simple Dockerfile recreates the issue (Only using Docker Desktop for Windows):
FROM debian/eol:wheezy
RUN apt-get update

**Comment by tianon** [comment]
https://github.com/debuerreotype/docker-debian-eol-artifacts/issues/5#issuecomment-1408961128 :eyes:

**Comment by twagaman-onebridge** [comment]
> 

Thank you! Sorry, I missed that.
